import { Project, User } from '@/types'
import { subDays } from 'date-fns'
import { calculateFinancials } from '@/lib/financial'

export const mockUsers: User[] = [
  {
    id: 'gestor_1',
    name: 'Ana Diretora',
    role: 'Gestor',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
  },
  {
    id: 'gerente_1',
    name: 'Carlos Silva',
    role: 'Gerente',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
  },
  {
    id: 'coord_1',
    name: 'João Coordenador',
    role: 'Coordenador',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
]

const rawProjects = [
  {
    id: 'proj_1',
    nome_projeto: 'Implementação ERP Odoo',
    id_gerente: 'gerente_1',
    nome_gerente: 'Carlos Silva',
    status: 'Em Andamento' as const,
    daysAgo: 15,
    receita_venda_produto: 50000,
    receita_venda_servico: 150000,
    custos_materiais: 20000,
    custos_servicos: 30000,
    custo_mao_de_obra: 40000,
    despesas_adm: 10000,
  },
  {
    id: 'proj_2',
    nome_projeto: 'Upgrade Infraestrutura de Redes',
    id_gerente: 'gerente_1',
    nome_gerente: 'Carlos Silva',
    status: 'Concluído' as const,
    daysAgo: 45,
    receita_venda_produto: 120000,
    receita_venda_servico: 40000,
    custos_materiais: 30000,
    custos_servicos: 10000,
    custo_mao_de_obra: 20000,
    despesas_adm: 5000,
  },
  {
    id: 'proj_3',
    nome_projeto: 'Migração Cloud AWS',
    id_gerente: 'gestor_1',
    nome_gerente: 'Ana Diretora',
    status: 'Em Andamento' as const,
    daysAgo: 10,
    receita_venda_produto: 0,
    receita_venda_servico: 200000,
    custos_materiais: 0,
    custos_servicos: 80000,
    custo_mao_de_obra: 60000,
    despesas_adm: 20000,
  },
  {
    id: 'proj_4',
    nome_projeto: 'Consultoria de BI',
    id_gerente: 'coord_1',
    nome_gerente: 'João Coordenador',
    status: 'Em Andamento' as const,
    daysAgo: 5,
    receita_venda_produto: 0,
    receita_venda_servico: 100000,
    custos_materiais: 0,
    custos_servicos: 20000,
    custo_mao_de_obra: 50000,
    despesas_adm: 10000,
  },
  {
    id: 'proj_5',
    nome_projeto: 'Desenvolvimento App Mobile',
    id_gerente: 'gerente_1',
    nome_gerente: 'Carlos Silva',
    status: 'Pausado' as const,
    daysAgo: 60,
    receita_venda_produto: 10000,
    receita_venda_servico: 150000,
    custos_materiais: 5000,
    custos_servicos: 40000,
    custo_mao_de_obra: 70000,
    despesas_adm: 15000,
  },
  {
    id: 'proj_6',
    nome_projeto: 'Auditoria de Segurança',
    id_gerente: 'gestor_1',
    nome_gerente: 'Ana Diretora',
    status: 'Concluído' as const,
    daysAgo: 120,
    receita_venda_produto: 0,
    receita_venda_servico: 80000,
    custos_materiais: 0,
    custos_servicos: 10000,
    custo_mao_de_obra: 30000,
    despesas_adm: 5000,
  },
  {
    id: 'proj_7',
    nome_projeto: 'Integração de APIs',
    id_gerente: 'coord_1',
    nome_gerente: 'João Coordenador',
    status: 'Em Andamento' as const,
    daysAgo: 25,
    receita_venda_produto: 20000,
    receita_venda_servico: 90000,
    custos_materiais: 5000,
    custos_servicos: 15000,
    custo_mao_de_obra: 35000,
    despesas_adm: 8000,
  },
  {
    id: 'proj_8',
    nome_projeto: 'Manutenção de Sistemas',
    id_gerente: 'gerente_1',
    nome_gerente: 'Carlos Silva',
    status: 'Em Andamento' as const,
    daysAgo: 2,
    receita_venda_produto: 0,
    receita_venda_servico: 50000,
    custos_materiais: 0,
    custos_servicos: 5000,
    custo_mao_de_obra: 20000,
    despesas_adm: 5000,
  },
]

export const mockProjects: Project[] = rawProjects.map((raw) => {
  const baseFinancials = {
    receitaProduto: raw.receita_venda_produto,
    receitaServico: raw.receita_venda_servico,
    custoMateriais: raw.custos_materiais,
    custoServicos: raw.custos_servicos,
    custoMaoDeObra: raw.custo_mao_de_obra,
    despesasAdm: raw.despesas_adm,
  }

  const financials = calculateFinancials(baseFinancials)

  return {
    id: raw.id,
    name: raw.nome_projeto,
    managerId: raw.id_gerente,
    managerName: raw.nome_gerente,
    status: raw.status,
    startDate: subDays(new Date(), raw.daysAgo).toISOString(),
    baseFinancials,
    financials,
    comments: [],
  }
})
