import { Project, User } from '@/types'
import { subDays } from 'date-fns'

export const mockUsers: User[] = [
  {
    id: 'gestor_1',
    name: 'Ana Diretora',
    role: 'Gestor',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=3',
  },
  {
    id: 'gerente_1',
    name: 'Carlos Silva',
    role: 'Gerente',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
  },
  {
    id: 'coord_1',
    name: 'João Coordenador',
    role: 'Coordenador',
    avatar: 'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  },
]

export const mockProjects: Project[] = [
  {
    id: 'proj_1',
    name: 'Implementação ERP Odoo',
    managerId: 'gerente_1',
    managerName: 'Carlos Silva',
    status: 'Em Andamento',
    startDate: subDays(new Date(), 15).toISOString(),
    baseFinancials: {
      receitaProduto: 50000,
      receitaServico: 150000,
      custoMateriais: 20000,
      custoServicos: 30000,
      custoMaoDeObra: 40000,
      despesasAdm: 10000,
    },
    financials: {
      vBruto: 200000,
      pis: 3300,
      cofins: 15200,
      iss: 7500,
      deducoes: 26000,
      rLiquida: 174000,
      mBruta: 84000,
      margemBrutaPercent: 42,
      cVendasTotal: 90000,
      lucroAntesImpostos: 74000,
      csll: 6660,
      irpj: 11100,
      mLiquida: 56240,
      margemLiquidaPercent: 28.12,
    },
    comments: [],
  },
  {
    id: 'proj_2',
    name: 'Upgrade Infraestrutura de Redes',
    managerId: 'gerente_1',
    managerName: 'Carlos Silva',
    status: 'Concluído',
    startDate: subDays(new Date(), 45).toISOString(),
    baseFinancials: {
      receitaProduto: 120000,
      receitaServico: 40000,
      custoMateriais: 80000,
      custoServicos: 10000,
      custoMaoDeObra: 20000,
      despesasAdm: 5000,
    },
    financials: {
      vBruto: 160000,
      pis: 2640,
      cofins: 12160,
      iss: 2000,
      deducoes: 16800,
      rLiquida: 143200,
      mBruta: 33200,
      margemBrutaPercent: 20.75,
      cVendasTotal: 110000,
      lucroAntesImpostos: 28200,
      csll: 2538,
      irpj: 4230,
      mLiquida: 21432,
      margemLiquidaPercent: 13.39,
    },
    comments: [],
  },
]
